{
  "apiVersion": "rbac.authorization.k8s.io/v1",
  "kind": "ClusterRole",
  "metadata": {
    "name": "stateful-artifact"
  },
  "rules": [
    {
      "apiGroups": ["fluidcr.dcnlab.com"],
      "resources": ["fluidcrmigrations"],
      "verbs": ["get", "list", "watch"]
    },
    {
      "apiGroups": ["fluidcr.dcnlab.com"],
      "resources": ["fluidcrmigrations/status"],
      "verbs": ["get", "patch"]
    },
    {
      "apiGroups": [
        "migration.dcnlab.com"
      ],
      "resources": [
        "restoreplans"
      ],
      "verbs": [
        "get",
        "list",
        "watch"
      ]
    },
    {
      "apiGroups": [
        "migration.dcnlab.com"
      ],
      "resources": [
        "restoreplans/status"
      ],
      "verbs": [
        "get",
        "update",
        "patch"
      ]
    }
  ]
}
