{
  "apiVersion": "cert-manager.io/v1",
  "kind": "Issuer",
  "metadata": {
    "name": "stateful-selfsigned",
    "namespace": "stateful-migration-system"
  },
  "spec": {
    "selfSigned": {}
  }
}
