{
  "apiVersion": "rbac.authorization.k8s.io/v1",
  "kind": "ClusterRole",
  "metadata": {
    "name": "stateful-member"
  },
  "rules": [
    {"apiGroups": [""], "resources": ["pods/exec"], "verbs": ["create"]},
    {"apiGroups": ["batch"], "resources": ["jobs"], "verbs": ["get", "list", "watch", "create"]},
    {"apiGroups": ["apps"], "resources": ["statefulsets"], "verbs": ["get"]},
    {"apiGroups": [""], "resources": ["persistentvolumeclaims", "persistentvolumes"], "verbs": ["get", "list", "watch"]},
    {"apiGroups": ["ml.dcn.ssu.ac.kr"], "resources": ["nodeprovisions"], "verbs": ["get", "list", "watch"]},
    {
      "apiGroups": ["fluidcr.dcnlab.com"],
      "resources": ["fluidcrmigrations"],
      "verbs": ["get"]
    },
    {
      "apiGroups": [
        "migration.dcnlab.com"
      ],
      "resources": [
        "restoreplans"
      ],
      "verbs": [
        "get",
        "list",
        "watch"
      ]
    },
    {
      "apiGroups": [
        "migration.dcnlab.com"
      ],
      "resources": [
        "restoreplans/status"
      ],
      "verbs": [
        "get",
        "patch",
        "update"
      ]
    },
    {
      "apiGroups": [
        ""
      ],
      "resources": [
        "pods"
      ],
      "verbs": [
        "get",
        "list",
        "watch",
        "delete"
      ]
    },
    {
      "apiGroups": [
        ""
      ],
      "resources": [
        "endpoints"
      ],
      "verbs": [
        "get",
        "list",
        "watch"
      ]
    },
    {
      "apiGroups": [
        ""
      ],
      "resources": [
        "nodes"
      ],
      "verbs": [
        "get",
        "list",
        "watch"
      ]
    },
    {
      "apiGroups": [
        "coordination.k8s.io"
      ],
      "resources": [
        "leases"
      ],
      "verbs": [
        "get",
        "list",
        "watch",
        "create",
        "update",
        "patch"
      ]
    }
  ]
}
